kind: Service
apiVersion: v1
metadata:
  name: helloworldservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8080
      nodePort: 30002
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: alexknipfer/hello-world
          ports:
            - containerPort: 8080