---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: weather-service
  name: weather-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: weather-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: weather-service
    spec:
      containers:
      - image: alexknipfer/weather-service
        imagePullPolicy: IfNotPresent
        name: weather-service
        ports:
        - containerPort: 8080
        env:
        - name: OPEN_WEATHER_API_KEY
          value: "4515a42ada398354247cd924a24db378"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: weather-service
  name: weather-service
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  fws-weather_mapping
      prefix: /getWeatherByZip/
      rewrite: /api/getWeatherByZip/
      service: weather-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: weather-service
  sessionAffinity: None
  type: ClusterIP